"""initial commit

Revision ID: dbf76d5d7084
Revises: faa482c1e292
Create Date: 2025-04-18 01:34:02.224891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf76d5d7084'
down_revision = 'faa482c1e292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'created_at')
    op.drop_column('authors', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('authors', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###
